#!/usr/bin/bash

all="false"
while getopts "a" opt ; do
    case $opt in
        a) all=true;;
    esac
done

default="#90707070"
#glyph_clock="\uF109"
glyph_clock=""
clock_text=${glyph_clock}
clock_color="#99802080"

# full date and time
#ret=$(date '+%a %d %b %Y %I:%M:%S %p %Z')

if [ $all = "true" ]; then
    notify-send "Calendar\n" "$(cal -w)"
else
    ret=$(date '+%a %I:%M %p')
    echo "%{A:asclock:}%{F${clock_color}}${clock_text}%{F${default}}${ret}%{A}"
fi
