#!/usr/bin/bash

interval=1
snoop=
format="%s"
callback="echo 'Please pass c argument'"
while getopts "si:f:c:" opt ; do
    case $opt in
        s) snoop=true;;
        i) interval=$OPTARG ;;
        f) format=$OPTARG ;;
        c) callback=$OPTARG ;;
    esac
done

if [ ! -z $snoop ]; then
    while true; do
        printf "$format\n" "$(${callback})"
        sleep $interval
    done
else
    eval ${callback}
fi
