#!/usr/bin/zsh
# TODO: we should use zsh because of weather_full need to be added newline

default="#90707070"

glyph_weather="\u263c"
weather_text=""
weather_color="#be9b7b00"

all="false"
while getopts "a" opt ; do
    case $opt in
        a) all=true;;
    esac
done

#TODO: to change code, please search google with "city yahoo weather", click on first link, and see number in url
city_code=8676
weather_full=$(curl --silent "http://weather.yahooapis.com/forecastrss?w=${city_code}&u=c")


if [ $all = "true" ]; then

    gif_url=$(echo $weather_full | sed -n '/^<img /p' | cut -d'"' -f2)
    gif_file=$(echo $gif_url | awk -F "/" '{print $NF}' | cut -d'.' -f1)
    [ ! -e /tmp/icons/${gif_file}.png ] && mkdir -p /tmp/icons && curl "${gif_url}" -o /tmp/icons/${gif_file}.gif && convert /tmp/icons/${gif_file}.gif /tmp/icons/${gif_file}.png

    # today weather
    today="Today: $(echo $weather_full | sed -ne '/Current Conditions/{n;p}' | sed -e 's/<BR \/>//')"

    weather_info=
    echo $weather_full | grep yweather:forecast | while read -r line; do
        day=$(echo $line | sed -r 's/<yweather:forecast day="(.*)" date="(.*)" low="(.*)" high="(.*)" text="(.*)" code="(.*)".*/\1/')
        low=$(echo $line | sed -r 's/<yweather:forecast day="(.*)" date="(.*)" low="(.*)" high="(.*)" text="(.*)" code="(.*)".*/\3/')
        high=$(echo $line | sed -r 's/<yweather:forecast day="(.*)" date="(.*)" low="(.*)" high="(.*)" text="(.*)" code="(.*)".*/\4/')
        text=$(echo $line | sed -r 's/<yweather:forecast day="(.*)" date="(.*)" low="(.*)" high="(.*)" text="(.*)" code="(.*)".*/\5/')
        weather_info="${weather_info}\n$(printf "%5s\t%3s C\t%3s C\t%s" ${day} ${low} ${high} ${text})"
    done

    notify-send -i "/tmp/icons/${gif_file}.png" "${today}" "$weather_info"
else
    weather_info=$(echo $weather_full | sed -ne '/Current Conditions/{n;p}' | sed -e 's/<BR \/>//')
    test -z "$weather_info" && echo "" || echo "%{A:ayforecast:}%{F${weather_color}}${weather_text} %{F${default}}$weather_info%{A}"
fi


